final prev
hik94dh/yard-frontend pull request #3
Opened 2017-06-13 15:25 UTC by hik94dh

2017-06-13 17:31 UTC, imevro requested changes

2017-06-13 17:31 UTC, evgenyrodionov commented on complex.html
> +	<header>
форматирование неправильное, переделать на 2 пробела вместо таба

2017-06-13 17:31 UTC, evgenyrodionov commented on css/style.css
> +body, html {
у файла мусорное форматирование, приведи в порядок

2017-06-13 19:50 UTC, hik94dh commented on css/style.css
> +body, html {
исправлено, летят коммиты

2017-06-13 21:21 UTC, imevro requested changes

2017-06-13 21:21 UTC, evgenyrodionov commented on complex.html
> +    <meta charset="UTF-8">
4 пробела → 2 пробела

2017-06-14 13:31 UTC, imevro requested changes
Плохо с неймингом

2017-06-14 13:31 UTC, evgenyrodionov commented on complex.html
> +  <link rel="stylesheet" type="text/css" href="css/normalize.css">
type с html5 стал не нужен

2017-06-14 13:31 UTC, evgenyrodionov commented on complex.html
> +      <h2 class="main-top_h2">Discover Our New Developments</h2>
h2 → title
ну и тому подобное

Что за привычка называть классы по тегам, а если мне тут нужно будет сделать h1?

2017-06-14 13:31 UTC, evgenyrodionov commented on complex.html
> +    <a href="#" class="main-content">
это карточка, а не маин-контент

2017-06-14 19:28 UTC, imevro requested changes

2017-06-14 19:28 UTC, evgenyrodionov commented on complex.html
> +  <section class="subheader">
промо скорее, не сабхедере

2017-06-14 19:28 UTC, evgenyrodionov commented on complex.html
> +  <section class="main">
Есть тег main, если на то пошло

2017-06-14 19:28 UTC, evgenyrodionov commented on complex.html
> +    <a href="#" class="main-card">
зачем тут префикс main? что он обозначает? Почему не просто card?

2017-06-14 19:28 UTC, evgenyrodionov commented on css/style.css
> +.main-top_p {
description, а не p

2017-06-14 19:28 UTC, evgenyrodionov commented on css/style.css
> +.main-top_title {
маин-топ-титле? Как мне понять из класса, к чему он относится?

2017-06-14 19:28 UTC, evgenyrodionov commented on css/style.css
> +footer {
футер не эксклюзивный тег, он может быть даже в карточке

2017-06-14 19:28 UTC, evgenyrodionov commented on css/style.css
> +footer {
не вешай стили на теги

2017-06-15 09:46 UTC, imevro requested changes

2017-06-15 09:46 UTC, evgenyrodionov commented on complex.html
> +    <div class="main">
hero-unit, jumbotron, banner, но не абстрактный мейн

2017-06-15 09:46 UTC, evgenyrodionov commented on complex.html
> +    <div class="main">
promo в конце концов

2017-06-15 10:24 UTC, evgenyrodionov commented
настрой гитконфиг или гитхаб, у тебя коммиты от левого человека

2017-06-15 10:24 UTC, imevro requested changes
я тебе дал на выбор 4 класса, а ты выбрал всё равно какой-то абстрактный КОНТЕНТ

список карточек это не контент? футер это не контент? навигация это не контент?

2017-06-15 10:52 UTC, hik94dh commented
1) Да, на рабочем и домашнем разные конфиги(
2) Promo уже есть, banner — ну какой это banner?  Ни одной графики в этом блоке нет.  А остальные сначала смутили своим переводом, но потом погуглил и понял, что подойдут.

2017-06-15 13:09 UTC, imevro approved these changes

2017-06-15 13:09 UTC, merged