create page 2
hik94dh/yard-frontend pull request #4
Opened 2017-06-15 20:23 UTC by hik94dh

2017-06-15 21:33 UTC, imevro requested changes
Фикси мерджконфликты 

И я не понял как у тебя страница ЖК в complexes, а список ЖК в complex

2017-06-16 09:40 UTC, evgenyrodionov commented
Кнопка контакт зе тим не тем шрифтом как в макете https://rawgit.com/hik94dh/yard-frontend/develop/complexes.html

2017-06-16 09:43 UTC, imevro requested changes

2017-06-16 09:43 UTC, evgenyrodionov commented on complexes.html
> +        <div class="col-xs-8 col-lg-9">
а зачем тут сетка вообще

2017-06-16 09:43 UTC, evgenyrodionov commented on complexes.html
> +        <div class="col-xs-8 col-lg-9">
контейнер понятно-то

2017-06-16 09:43 UTC, evgenyrodionov commented on complexes.html
> +          <img src="img/compass-development-logo.svg" class="compass-development-logo">
.promo > .promo-logo > .compass-development-logo?

2017-06-16 09:43 UTC, evgenyrodionov commented on complexes.html
> +        <a href="#" class="hero-unit_btn-link">Contact The Team</a>
а зачем ссылка в кнопке

2017-06-16 09:43 UTC, evgenyrodionov commented on css/style.css
> +h1, h2, h3, h4, p {
это что

2017-06-16 09:43 UTC, evgenyrodionov commented on css/style.css
> +/* Start Page 2 */
вынеси это в отдельный файл complex.css

2017-06-16 13:28 UTC, evgenyrodionov commented
Тень при ховере не как в макете

2017-06-16 13:31 UTC, imevro requested changes

2017-06-16 13:31 UTC, evgenyrodionov commented on complexes.html
> +      <center>
нет

2017-06-16 13:31 UTC, evgenyrodionov commented on complexes.html
> +      <center>
этот тег давно запрещен

2017-06-16 13:31 UTC, evgenyrodionov commented on complexes.html
> +        <a href="#">
тут не нужна ссылка

2017-06-16 13:31 UTC, evgenyrodionov commented on complexes.html
> +              <img src="img/combined-shape.svg" class="combined-shape">
combined-shape? what the fuck

2017-06-16 13:31 UTC, evgenyrodionov commented on complexes.html
> +          <h4 class="footer-title footer-hr">Компания</h4>
что за footer-hr

2017-06-16 13:31 UTC, evgenyrodionov commented on complexes.html
> +            <a href="#" class="footer-menu">Команда</a><br>
1) бр запрещен
2) что за footer-menu на ссылке?

2017-06-16 13:31 UTC, evgenyrodionov commented on css/style.css
> +.header_wrapper{
куда проебал отступ между словом и {

2017-06-16 16:37 UTC, hik94dh commented on complexes.html
> +          <h4 class="footer-title footer-hr">Компания</h4>
Отсылка к тэгу hr, подходит же название! Ну или line

2017-06-16 18:29 UTC, evgenyrodionov commented on complexes.html
> +          <h4 class="footer-title footer-hr">Компания</h4>
Лайн лучше

2017-06-16 18:39 UTC, imevro requested changes
ну и тень ебучая

2017-06-16 18:39 UTC, evgenyrodionov commented on complexes.html
> +      <div class="header_wrapper">
header_wrapper, но header-menu?

2017-06-16 18:39 UTC, evgenyrodionov commented on complexes.html
> +        <img src="img/promo-logo.svg" class="promo-logo">
почему 4 пробела отступ

2017-06-16 21:33 UTC, imevro approved these changes

2017-06-16 21:33 UTC, merged

2017-06-16 21:34 UTC, evgenyrodionov commented
Переключись в мастер, сделай гит пулл --ребейс, затем новый бранч девелопа