create react project
hik94dh/yard-frontend pull request #6
Opened 2017-06-19 13:20 UTC by hik94dh

2017-06-19 21:15 UTC, imevro requested changes
короче отступам пизда

2017-06-19 21:15 UTC, evgenyrodionov commented on package.json
> +  "name": "my-app",
конкретнее

2017-06-19 21:15 UTC, evgenyrodionov commented on public/index.html
> +    <title>React App</title>
не-а

2017-06-19 21:15 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
опять же

2017-06-19 21:15 UTC, evgenyrodionov commented on public/manifest.json
> +  "name": "Create React App Sample",
тоже меняй

2017-06-19 21:15 UTC, evgenyrodionov commented on src/Cards/Card.js
> +import build1 from './i/build.jpg';
1) что такое build1?
2) постфиксуй как `*Img`

2017-06-19 21:15 UTC, evgenyrodionov commented on src/Cards/Card.js
> +      <a href="" className="card">
такс-такс, опять наши любимые отступы

2017-06-19 21:15 UTC, evgenyrodionov commented on src/Cards/CardInfo2.js
> +      //   <div className="card-info">
ты думаешь оно заработает?

2017-06-20 21:10 UTC, imevro requested changes

2017-06-20 21:10 UTC, evgenyrodionov commented on package.json
> +  "name": "Compass",
с нижней буквы

2017-06-20 21:10 UTC, evgenyrodionov commented on public/index.html
> +    <title>Сайт недвижимости «Compass»</title>
агентства мб

2017-06-20 21:10 UTC, evgenyrodionov commented on src/App.js
> +import Complexes from './Complexes/Complexes'
по архитектуре в телеграфе есть

2017-06-20 21:10 UTC, evgenyrodionov commented on src/Complexes/Card.js
> +      <CardInfo id={1} geo="SOUTH BEACH, SAN FRANCISCO" title="The Harrison" text=" The Lewis Steel Building is a masterful industrial conversion located in the heart of Williamsburg. Located at 76 N
text → пропс чилдрен, гугли

2017-06-20 21:10 UTC, evgenyrodionov commented on src/Complexes/Card.js
> +      <CardInfo id={1} geo="SOUTH BEACH, SAN FRANCISCO" title="The Harrison" text=" The Lewis Steel Building is a masterful industrial conversion located in the heart of Williamsburg. Located at 76 N
не тайтл, а имя ЖК

2017-06-20 21:10 UTC, evgenyrodionov commented on src/Complexes/Card.js
> +      <CardInfo id={1} geo="SOUTH BEACH, SAN FRANCISCO" title="The Harrison" text=" The Lewis Steel Building is a masterful industrial conversion located in the heart of Williamsburg. Located at 76 N
не гео, а адрес

2017-06-20 21:10 UTC, evgenyrodionov commented on src/Complexes/CardInfo.js
> +  display: -webkit-box;
КРА сам префиксует

2017-06-20 21:10 UTC, evgenyrodionov commented on src/Complexes/CardInfo.js
> +      <div className="card-info">
почему тут классы, если у нас стайлед компонентс?

2017-06-20 21:10 UTC, evgenyrodionov commented on src/Complexes/Complexes.js
> +import Card from './Card';
если по неймингу карточка одна, почему у тебя внутри их 3?

2017-06-22 09:04 UTC, hik94dh commented on src/Complexes/Card.js
> +      <CardInfo id={1} geo="SOUTH BEACH, SAN FRANCISCO" title="The Harrison" text=" The Lewis Steel Building is a masterful industrial conversion located in the heart of Williamsburg. Located at 76 N
Тут ещё не закончил + у меня картинки не подтягиваются, разбираюсь.

2017-06-22 10:00 UTC, evgenyrodionov commented on src/Complexes/CardInfo.js
> +  display: -webkit-box;
соу

2017-06-22 10:00 UTC, imevro requested changes

2017-06-22 10:00 UTC, evgenyrodionov commented on src/Complexes/CardInfo.js
> +  display: -webkit-box;
соу?

2017-06-22 13:37 UTC, imevro requested changes
если у тебя хранятся пикчи в `/public/i`, то ты их подключаешь через 
```
src={`${process.env.PUBLIC_URL}/i/image.png`}
```

2017-06-22 13:37 UTC, evgenyrodionov commented on src/Complex/Gallery.js
> +        <Image src={process.env.PUBLIC_URL + '../..i/gallery-5' +'.png'}  alt="building" />
не понял что случилось с путями и вообще со строкой

2017-06-22 21:43 UTC, imevro requested changes
https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-assets-outside-of-the-module-system

почитай внимательно очень

2017-06-23 21:09 UTC, imevro requested changes
все еще жду когда ты разберешься с пикчами

2017-06-23 21:09 UTC, evgenyrodionov commented on src/App.js
> +import Complexes from './Complexes/List/Index'
INDEX можно опустить и он должен быть с маленькой буквы для этого

2017-06-24 09:13 UTC, imevro requested changes

2017-06-24 09:13 UTC, evgenyrodionov commented on src/Complexes/Show/Guide.jsx
> +            <Image src={process.env.PUBLIC_URL + 'i/guide' + '.jpg'} alt="guide" />
а зачем ты тут порвал гайд и .жпг

2017-06-24 09:22 UTC, imevro approved these changes

2017-06-24 14:27 UTC, merged